<?php
/** @var $block \Netzexpert\OfferSpecialEdition\Block\Checkout\Cart\Form */
?>
<form id="send-quote-form-general" class="form_email" method="post" xmlns="http://www.w3.org/1999/html">
    <input type="hidden" name="offer_id" value="<?= $block->getOfferId(); ?>" />
    <input name="email" placeholder="<?php echo __('Enter email address')?>" title="<?php /* @escapeNotVerified */ echo __('Email') ?>"
           class="input-email" type="email" data-validate="{required:true, 'validate-email':true, equalTo:'#email'}"/>
    <input name="name" placeholder="Enter name and surname" title="<?php /* @escapeNotVerified */ echo __('Name') ?>"
           value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>"
           class="input-name" type="text" data-validate="{required:true}"/>
    <textarea name="comment" placeholder="Leave your comment here" title="<?php /* @escapeNotVerified */ echo __('Comment') ?>"
              class="comment" type="text" data-validate="{required:true}"></textarea>
    <?php if ($block->checkCustomer() == true):?>
        <select name="template" class="form_template_request" type="text">
            <?php
            foreach ($block->getAvailableTemplates() as $template) :?>
                <option value="<?= $block->escapeHtml($template['value']) ?>"><?= $block->escapeHtml($template['label']) ?></option>
            <?php endforeach; ?>
        </select>
    <?php elseif ($block->checkCustomer() == false):?>
        <script>
            require(['jquery'],function() {
                jQuery(".form_template_request").hide();
            })
        </script>
    <?php $templateValue = $block->getTemplateNonRegisteredUser()?>
    <input name="template" type="hidden" value="<?= $block->escapeHtml(array_pop($templateValue)['value'])?>"/>
    <?php endif; ?>
    <button id="send-quote" type="submit" title="<?= /* @escapeNotVerified */ __('Send Cart') ?>" class="action_button">
        <span><?= /* @escapeNotVerified */ __('Send Cart') ?></span>
    </button>
    <div class="information-text">
        <blockquote>
        "um Ihre Zufriedenheit während des gesamten Bestellprozesses weiterhin gewährleisten zu können, weißen wir an dieser Stelle darauf hin, dass wir die "Kauftaste" entfernen mussten und mit „Anfrage senden“ ersetzen. Dies hat den Grund, dass bevor eine Bestellung tatsächlich in unserem System eingeht, wir zu prüfen haben, ob die von Ihnen gewünschte Rohstoffe, welche für Ihre Schmuckstücke verwendet und produziert werden vorhanden sind. Erst nach erfolgreichem Abgleich, Prüfung und Freigabe der Materialien, werden Sie in der Regel innerhalb 24h für die Bezahlung freigeschalten. Anschließend können Sie die von Ihnen getätigte Bestellung abschließen."
        </blockquote>
    </div>
</form>


<script>
    require(['jquery'],function() {
        jQuery(document).ready(function () {
            jQuery("#send-quote-form-general").submit(function () {
                var data = jQuery(this).serialize();
                jQuery.ajax({
                    url: '<?= $block->getFormUrl() ?>',
                    type: "POST",
                    data: data,
                    showLoader: true,
                    context: jQuery('body'),
                    cache: false,
                    success: function(){
                        location.reload();
                    }
                });
                    return false;
            });
        });
    });
</script>
